### PR TITLE
ci: fix opa violation: docker credentials

### PR DESCRIPTION
**Pull request by SpectreVert**

### CODE REVIEW

**Comment by aliculPix4D** [comment]
Lets wait for the pipeline setter to see if there is more violations...

**Comment by iAmoric** [comment]
> Lets wait for the pipeline setter to see if there is more violations...

I think pipeline setter is not activated here

**Comment by aliculPix4D** [comment]
so note that one needs to create/delete pipelines multiple time to see if you fixed all violations.

You only see the violation the first time you set the pipeline or if you update it.

**Comment by SpectreVert** [comment]
Looks good to me..

**Review by aliculPix4D — APPROVED** [review]

**Review by iAmoric — APPROVED** [review]

**Pull request merged**
